<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Spotify for Creators / Podcasters RSS Feed
    |--------------------------------------------------------------------------
    |
    | The source-of-truth RSS feed URL generated by Spotify / Anchor.
    | When new episodes are published on Spotify, our website pulls
    | the episode metadata, CDN audio stream, duration, and artwork from here.
    |
    */
    'spotify_rss_url' => env('SPOTIFY_PODCAST_RSS_URL', 'https://anchor.fm/s/116518364/podcast/rss'),

    /*
    |--------------------------------------------------------------------------
    | Auto Sync Schedule Interval
    |--------------------------------------------------------------------------
    */
    'auto_sync' => env('SPOTIFY_PODCAST_AUTO_SYNC', true),
];
